/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

char *host;
CLIENT *client;

// uses output from the fortune program as client message
char* exe_fortune();

void send_msgs(int id);
void get_msgs(int id);

int main(int argc, char *argv[]){
    int id = getpid();

    if (argc < 2) {
        printf("Usage: %s server host\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    host = argv[1];
    if ((client = clnt_create(host, RPC_PRG, RPC_V1, "tcp")) == (CLIENT *) NULL) {
        clnt_pcreateerror(host);
        exit(EXIT_FAILURE);
    }

    // send 5 messages to the server
    int i = 0;
    while(i < 5) {
        sleep(1);
        send_msgs(id);
        i++;
    }

    sleep(5);

    // get 10 messages from the server
    i = 0;
    while (i < 10) {
        sleep(1);
        get_msgs(id);
        i++;
    }

    exit(EXIT_SUCCESS);
}

void send_msgs(int id) {
    int *return_value;

    // initialize data that will be sent to server i.e. client id and message
    struct client_data data;
    data.client_id = id;
    strcpy(data.client_msg, exe_fortune());

    printf("Client #%d: calling Put.\n", id);
    // send a message to the server
    return_value = put_1(&data, client);

    if (*return_value == 0) {
        printf("Client #%d: Put successful. Status code: %d\n", id, *return_value);
    }
}

void get_msgs(int id) {
    struct response *return_value;
    int filler;

    printf("Calling Get.\n");
    return_value = get_1(&id, client);

    if (return_value->status_code != 0) {
        printf("Client #%d: There were no messages for me. Status code: %d\n", id, return_value->status_code);
    }
    else {
        printf("Client #%d: Retrieved message: %s, Status code: %d\n", id, return_value->message, return_value->status_code);
    }
}

char* exe_fortune() {
    FILE *fp;
    static char path[2048];
    int status;

    // Open the command for reading
    fp = popen("/usr/games/fortune", "r");
    if (fp == NULL) {
        printf("Failed to run command: fortune\n" );
        exit(1);
    }

    // Read the output a line at a time
    while (fgets(path, sizeof(path)-1, fp) != NULL) {
        // do nothing
    }

    // close
    status = pclose(fp);
    if(status == -1) {
        perror("pclose()");
        exit(EXIT_FAILURE);
    }
    return path;
}
