/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct client_data {
	int client_id;
	char client_msg[10];
};
typedef struct client_data client_data;

#define RPC_PRG 0x20000001
#define RPC_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define put 1
extern  int * put_1(struct client_data *, CLIENT *);
extern  int * put_1_svc(struct client_data *, struct svc_req *);
#define get 2
extern  int * get_1(void *, CLIENT *);
extern  int * get_1_svc(void *, struct svc_req *);
extern int rpc_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define put 1
extern  int * put_1();
extern  int * put_1_svc();
#define get 2
extern  int * get_1();
extern  int * get_1_svc();
extern int rpc_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client_data (XDR *, client_data*);

#else /* K&R C */
extern bool_t xdr_client_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
