/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

char* get_time();

client_data messages[100] = {{-1, ""}};
int client_req_num = 0;
int count = 0;
int current_client_id;

int *put_1_svc(struct client_data *argp, struct svc_req *rqstp) {
	static int  result;
	int id = argp->client_id;
	current_client_id = argp->client_id;

	messages[client_req_num] = *argp;
	count++;

	result = printf("Server Says-- Put() Request: \"%s\" from Client_%d at %s\n", messages[client_req_num].client_msg,
					messages[client_req_num].client_id, get_time());
	client_req_num++;
	return (&result);
}

int *get_1_svc(void *argp, struct svc_req *rqstp) {
	static int  result;

	if(count == 0) {
		result = -1;
		return &result;
	}

	int found_msg = 0;
	int i;
	for(i = 0; i < client_req_num; i++) {
		int id = messages[i].client_id;

		// do not retrieve your own message
		if(id != current_client_id) {
			found_msg = 1;
			result = printf("Server Says-- Get() Request at %s. Message: \"%s\"\n", get_time(), messages[i].client_msg);
			break;
		}
	}

	if(found_msg == 0) {
		result = -1;
	}
	return &result;
}


char* get_time() {
	time_t rawtime;
	struct tm *timeinfo;

	time (&rawtime);
	timeinfo = localtime(&rawtime);
	return asctime(timeinfo);
}