/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

#define MAX_CLIENTS 3

char* get_time();
int check_for_multiple_clients(int id);

client_data messages[100] = {{-1, ""}};
int active_clients[3] = {0, 0, 0};

int client_req_num = 0;
int current_client_id = 0;
int client_count = 0;

int check_for_multiple_clients();
char* get_time();
int add_client(int client_id);

int *put_1_svc(struct client_data *argp, struct svc_req *rqstp) {
	static int  result;
	int id = argp->client_id;

	current_client_id = argp->client_id;
	printf("Put Request from Client #%d, Time: %s\n", current_client_id, get_time());

	if(client_req_num == 3) {
		// there are already 3 clients communicating with the server
		result = -1;
	}
	else {
		// store the message
		messages[client_req_num] = *argp;
		result = 0;
	}
	client_req_num++;
	return (&result);
}

struct response *get_1_svc(int *id, struct svc_req *rqstp) {
	static struct response result;
	current_client_id = *id;
	printf("Get Request from Client #%d, Time: %s\n", current_client_id, get_time());

	if(add_client(current_client_id) == -1 || check_for_multiple_clients() == -1) {
		result.status_code = -1;
		return &result;
	}

	int found_msg = 0;
	int i;

	while(found_msg == 0) {
		int rand_val = rand() % (client_req_num - 1);
		int retrieved_data_id = messages[rand_val].client_id;

		if(client_req_num <= 1) {
			// You are the first client to request a msg. Only your msg is saved at this point.
			result.status_code = -1;
			return &result;
		}
		else if(retrieved_data_id != current_client_id) {
			found_msg = 1;
			result.status_code = 0;
			strcpy(result.message, messages[rand_val].client_msg);
		}
	}

	return &result;
}

// this function checks that there are at least 2 clients on the server
// if there is, we know a client can retrieve a message that is not his.
int check_for_multiple_clients() {
	int count = 0;

	int i;
	for(i = 0; i < MAX_CLIENTS; i++) {
		if(active_clients[i] != 0) {
			count++;
		}
	}

	if(count >= 2) {
		return 0;
	}
	else {
		return -1;
	}
}

char* get_time() {
	time_t rawtime;
	struct tm *timeinfo;

	time (&rawtime);
	timeinfo = localtime(&rawtime);
	return asctime(timeinfo);
}

// check if there is room on the server for another client
// the server allows at most 3 clients
int add_client(int client_id) {
	int i;
	for(i = 0; i < MAX_CLIENTS; i++) {
		if(active_clients[i] == 0) {
			active_clients[i] = client_id;
			client_count++;
			return 0;
		}
		else {
			if(active_clients[i] == client_id) {
				return 0;
			}
		}
	}

	// there are already 3 clients using the server
	return -1;
}